// ============================================================
// Demo-Daten für /demo — realistisch wirkende Beispiel-Leads,
// -Profile, -Skripte und -Termine OHNE echte Kundendaten.
// Wird nur von den Demo-Seiten genutzt (kein Supabase nötig).
// ============================================================
import type { Appointment, CallNote, Lead, Profile, Script } from '@/lib/types'

const NOW = '2026-07-01T09:00:00.000Z'

function makeProfile(p: Partial<Profile> & Pick<Profile, 'id' | 'email' | 'full_name' | 'role'>): Profile {
  return {
    avatar_url: null,
    created_at: NOW,
    updated_at: NOW,
    ...p,
  }
}

export const MOCK_PROFILES: Record<'opener' | 'setter' | 'closer', Profile> = {
  opener: makeProfile({ id: 'profile-opener', email: 'opener@demo.hk', full_name: 'Nick Hinze', role: 'opener' }),
  setter: makeProfile({ id: 'profile-setter', email: 'setter@demo.hk', full_name: 'Luis Kummer', role: 'setter' }),
  closer: makeProfile({ id: 'profile-closer', email: 'closer@demo.hk', full_name: 'Luis Kummer', role: 'closer' }),
}

function makeNote(n: Partial<CallNote> & Pick<CallNote, 'id' | 'lead_id' | 'role_context'>): CallNote {
  return {
    user_id: 'profile-opener',
    call_result: null,
    interest_level: null,
    interest_topics: null,
    email_confirmed: false,
    preferred_contact_channel: null,
    appointment_requested: false,
    appointment_at: null,
    decision_makers_needed: null,
    objections: null,
    raw_note: null,
    structured_summary: null,
    next_step: null,
    created_at: NOW,
    ...n,
  }
}

function makeLead(l: Partial<Lead> & Pick<Lead, 'id' | 'company_name' | 'status'>): Lead {
  return {
    contact_name: null,
    role_title: null,
    phone: null,
    email: null,
    website: null,
    instagram: null,
    linkedin: null,
    industry: null,
    lead_source: 'Demo',
    lead_score: null,
    assigned_to: null,
    closer: null,
    pain_guess: null,
    entry_angle: null,
    last_contact_at: null,
    next_step: null,
    followup_at: null,
    appointment_at: null,
    decision_maker_status: null,
    preferred_contact_channel: null,
    last_note: null,
    do_not_contact: false,
    opt_out_at: null,
    opt_out_reason: null,
    relevance_reason: null,
    recommended_module_keys: null,
    created_at: NOW,
    updated_at: NOW,
    ...l,
  }
}

export const MOCK_LEADS: Lead[] = [
  makeLead({
    id: 'lead-1',
    company_name: 'Malermeister Kaufmann GmbH',
    contact_name: 'Stefan Kaufmann',
    role_title: 'Inhaber',
    phone: '+49 2261 123456',
    email: 'info@malermeister-kaufmann.de',
    website: null,
    industry: 'Handwerk / Maler',
    status: 'Zu kontaktieren',
    lead_score: 'A',
    entry_angle: 'Website',
    pain_guess: 'Keine eigene Website — Neukunden finden den Betrieb online nicht.',
    relevance_reason: '25 Mitarbeiter, volle Auftragsbücher nur über Mundpropaganda — online unsichtbar.',
    opener_pitch: 'Mir ist aufgefallen, dass man Ihren Betrieb online kaum findet, obwohl Sie in Gummersbach einen sehr guten Ruf haben.',
    lead_source: 'Lead Radar',
  }),
  makeLead({
    id: 'lead-2',
    company_name: 'Physiotherapie Bergland',
    contact_name: 'Anna Weber',
    role_title: 'Praxisleitung',
    phone: '+49 2261 654321',
    email: 'praxis@physio-bergland.de',
    website: 'https://physio-bergland.de',
    industry: 'Gesundheit',
    status: 'Nicht erreicht',
    lead_score: 'B',
    entry_angle: 'Social Media',
    pain_guess: 'Instagram-Kanal seit 8 Monaten inaktiv, Terminbuchung nur telefonisch.',
    last_contact_at: '2026-06-28T10:30:00.000Z',
    next_step: 'Zweiter Anrufversuch am Vormittag',
    lead_source: 'Empfehlung',
  }),
  makeLead({
    id: 'lead-3',
    company_name: 'Finke Gebäudetechnik GmbH',
    contact_name: 'Markus Finke',
    role_title: 'Geschäftsführer',
    phone: '+49 2264 987654',
    email: 'm.finke@finke-gebaeudetechnik.de',
    website: 'https://finke-gebaeudetechnik.de',
    industry: 'SHK / Gebäudetechnik',
    status: 'Closer-Call geplant',
    lead_score: 'A',
    entry_angle: 'KI-Zeitersparnis',
    pain_guess: 'Büro versinkt in Angebots- und Rechnungspapierkram, 2 Teilzeitkräfte nur für Verwaltung.',
    relevance_reason: '40 Mitarbeiter, wächst stark, Verwaltung skaliert nicht mit.',
    appointment_at: '2026-07-03T13:00:00.000Z',
    opener_pitch: 'Viele SHK-Betriebe Ihrer Größe verlieren pro Woche einen ganzen Arbeitstag an vermeidbare Verwaltungsarbeit.',
    setter_context: 'Sehr offen, will konkrete Zahlen sehen. Entscheidet gemeinsam mit Frau Finke (Prokuristin).',
    closer_context: 'Budget vorhanden, Angebotsprozess automatisieren ist Prio 1. Wettbewerber-Angebot liegt vor (unkonkret).',
    call_notes: [
      makeNote({
        id: 'note-3a',
        lead_id: 'lead-3',
        role_context: 'Opener',
        call_result: 'Interessiert',
        interest_level: 8,
        interest_topics: ['KI-Zeitersparnis', 'Automationen & CRM'],
        raw_note: 'Herr Finke direkt erreicht. Großes Thema: Angebote dauern 3–4 Tage. Will Experten-Call.',
        structured_summary: 'Entscheider erreicht, hoher Leidensdruck in der Verwaltung, Experten-Call vereinbart.',
        next_step: 'Experten-Call mit Setter',
        email_confirmed: true,
        appointment_requested: true,
      }),
      makeNote({
        id: 'note-3b',
        lead_id: 'lead-3',
        role_context: 'Setter',
        user_id: 'profile-setter',
        call_result: 'Qualifiziert für Closer',
        interest_level: 9,
        interest_topics: ['KI-Zeitersparnis'],
        raw_note: 'Prozesse durchgesprochen: Angebotserstellung, Rechnungslauf, Materialbestellung. Frau Finke muss in den Closer-Call.',
        structured_summary: 'Klarer Pain (Verwaltung), Budgetrahmen realistisch, beide Entscheider im Strategiegespräch.',
        decision_makers_needed: 'Frau Finke (Prokuristin)',
        next_step: 'Strategiegespräch mit Closer',
        email_confirmed: true,
      }),
    ],
  }),
  makeLead({
    id: 'lead-4',
    company_name: 'DataFlow Consulting',
    contact_name: 'Sarah Brandt',
    role_title: 'Geschäftsführerin',
    phone: '+49 221 5551234',
    email: 's.brandt@dataflow-consulting.de',
    website: 'https://dataflow-consulting.de',
    industry: 'IT-Beratung',
    status: 'Angebot vorbereiten',
    lead_score: 'A',
    entry_angle: 'Komplettangebot',
    pain_guess: 'Gute Auslastung über Bestandskunden, aber kein planbarer Neukunden-Kanal.',
    appointment_at: '2026-07-05T09:30:00.000Z',
    setter_context: 'Analytisch, will Roadmap statt Einzelmaßnahmen.',
    closer_context: 'Positionierung + Website + LinkedIn als System. Angebot bis Freitag zugesagt.',
    call_notes: [
      makeNote({
        id: 'note-4a',
        lead_id: 'lead-4',
        role_context: 'Opener',
        call_result: 'Termin vereinbart',
        interest_level: 7,
        raw_note: 'Frau Brandt kennt das Problem, hatte schon 2 Agenturen — beide nur Einzelmaßnahmen.',
        structured_summary: 'Skeptisch gegenüber Agenturen, sucht ganzheitlichen Ansatz.',
        next_step: 'Experten-Call',
        email_confirmed: true,
        appointment_requested: true,
      }),
      makeNote({
        id: 'note-4b',
        lead_id: 'lead-4',
        role_context: 'Setter',
        user_id: 'profile-setter',
        call_result: 'Qualifiziert für Closer',
        interest_level: 8,
        raw_note: 'System-Gedanke kam sehr gut an. Entscheidet allein.',
        structured_summary: 'Qualifiziert, ganzheitliches Wachstumssystem, entscheidet allein.',
        next_step: 'Strategiegespräch',
        email_confirmed: true,
      }),
    ],
  }),
  makeLead({
    id: 'lead-5',
    company_name: 'Autohaus Sommer',
    contact_name: 'Jens Sommer',
    role_title: 'Inhaber',
    phone: '+49 2262 445566',
    industry: 'KFZ-Handel',
    status: 'Interessiert',
    lead_score: 'B',
    entry_angle: 'Social Media',
    pain_guess: 'Fahrzeug-Angebote nur auf mobile.de, kein eigener Kanal, junge Käufer fehlen.',
    last_contact_at: '2026-06-30T14:00:00.000Z',
    next_step: 'Experten-Call-Termin vorschlagen',
    lead_source: 'Cold Call',
  }),
  makeLead({
    id: 'lead-6',
    company_name: 'Steuerkanzlei Voss & Partner',
    contact_name: 'Dr. Claudia Voss',
    role_title: 'Partnerin',
    email: 'voss@kanzlei-voss.de',
    industry: 'Steuerberatung',
    status: 'Setter-Call geplant',
    lead_score: 'A',
    entry_angle: 'KI-Zeitersparnis',
    appointment_at: '2026-07-02T11:00:00.000Z',
    pain_guess: 'Mandantenkommunikation und Belegaufbereitung fressen die Kanzlei auf.',
    lead_source: 'Lead Radar',
  }),
  makeLead({
    id: 'lead-7',
    company_name: 'Zimmerei Holzmann',
    contact_name: 'Peter Holzmann',
    role_title: 'Inhaber',
    phone: '+49 2263 778899',
    industry: 'Handwerk / Zimmerei',
    status: 'Neu',
    lead_score: 'C',
    entry_angle: 'Website',
    pain_guess: 'Website von 2011, nicht mobilfähig.',
    lead_source: 'Lead Radar',
  }),
  makeLead({
    id: 'lead-8',
    company_name: 'Restaurant Bergblick',
    contact_name: 'Maria Konstantinou',
    role_title: 'Inhaberin',
    phone: '+49 2261 334455',
    industry: 'Gastronomie',
    status: 'Angebot gesendet',
    lead_score: 'B',
    entry_angle: 'Lokale Sichtbarkeit',
    next_step: 'Nachfassen am Donnerstag',
    followup_at: '2026-07-04T10:00:00.000Z',
    closer_context: 'Angebot: Google-Profil + Website + Reservierungsstrecke. Entscheidet mit Ehemann.',
  }),
  makeLead({
    id: 'lead-9',
    company_name: 'Elektro Brandt GmbH',
    contact_name: 'Thomas Brandt',
    role_title: 'Geschäftsführer',
    phone: '+49 2264 112233',
    industry: 'Elektrohandwerk',
    status: 'Follow-up',
    lead_score: 'B',
    entry_angle: 'Recruiting',
    pain_guess: 'Findet keine Gesellen — Ausschreibungen laufen ins Leere.',
    followup_at: '2026-07-08T09:00:00.000Z',
    closer_context: 'Wartet auf Freigabe des Jahresbudgets (KW 28).',
  }),
  makeLead({
    id: 'lead-10',
    company_name: 'Setter qualifiziert Beispiel — Küchenstudio Lang',
    contact_name: 'Birgit Lang',
    role_title: 'Inhaberin',
    phone: '+49 2261 998877',
    industry: 'Einzelhandel / Küchen',
    status: 'Setter qualifiziert',
    lead_score: 'A',
    entry_angle: 'Anfragen',
    pain_guess: 'Ausstellungsbesuche brechen ein, keine Online-Anfragen.',
    next_step: 'Closer-Termin vereinbaren',
  }),
]

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'appt-1',
    lead_id: 'lead-3',
    closer: 'profile-closer',
    appointment_at: '2026-07-03T13:00:00.000Z',
    appointment_type: 'Closer-Call',
    attendees: ['Markus Finke', 'Frau Finke (Prokuristin)'],
    customer_email: 'm.finke@finke-gebaeudetechnik.de',
    status: 'Bestätigt',
    calendar_event_id: null,
    confirmation_email_status: 'gesendet',
    reminder_24h_status: 'ausstehend',
    reminder_1h_status: 'ausstehend',
    notes: 'Fokus: Angebotsprozess automatisieren, ROI-Rechnung mitbringen.',
    created_at: NOW,
    lead: MOCK_LEADS.find((l) => l.id === 'lead-3'),
  },
  {
    id: 'appt-2',
    lead_id: 'lead-4',
    closer: 'profile-closer',
    appointment_at: '2026-07-05T09:30:00.000Z',
    appointment_type: 'Closer-Call',
    attendees: ['Sarah Brandt'],
    customer_email: 's.brandt@dataflow-consulting.de',
    status: 'Geplant',
    calendar_event_id: null,
    confirmation_email_status: 'gesendet',
    reminder_24h_status: 'ausstehend',
    reminder_1h_status: 'ausstehend',
    notes: 'Roadmap-Entwurf zeigen (Positionierung → Website → LinkedIn).',
    created_at: NOW,
    lead: MOCK_LEADS.find((l) => l.id === 'lead-4'),
  },
]

function makeScript(s: Partial<Script> & Pick<Script, 'id' | 'role' | 'title'>): Script {
  return {
    entry_angle: null,
    industry: null,
    opening_line: null,
    main_body: null,
    closing_line: null,
    objection_handling: [],
    is_active: true,
    script_type: 'master',
    situation: null,
    parent_script_id: null,
    owner_user_id: null,
    status: 'approved',
    version: 1,
    relevance_line: null,
    core_question: null,
    transition_line: null,
    call_goal: null,
    full_script: null,
    required_notes_json: [],
    positioning: null,
    method_name: null,
    qualifying_questions_json: [],
    tone_guidance: null,
    created_by: null,
    approved_by: null,
    approved_at: null,
    rejection_note: null,
    created_at: NOW,
    updated_at: NOW,
    ...s,
  }
}

export const MOCK_SCRIPTS: Script[] = [
  makeScript({
    id: 'script-1',
    role: 'Opener',
    title: 'Opener — Website fehlt / schwach',
    entry_angle: 'Website',
    situation: 'website',
    relevance_line: 'Mir ist aufgefallen, dass man Ihr Unternehmen online kaum findet, obwohl Sie regional einen starken Ruf haben.',
    core_question: 'Wie kommen aktuell neue Kunden auf Sie zu — und reicht Ihnen das?',
    transition_line: 'Genau dafür bieten wir einen kostenfreien Experten-Call an, in dem unser Fachmann Ihre Online-Sichtbarkeit konkret analysiert.',
    call_goal: 'Experten-Call-Termin vereinbaren',
    objection_handling: [
      { objection: 'Wir haben genug Aufträge.', response: 'Verstehe ich — genau dann lohnt es sich, die profitabelsten Anfragen gezielt auszuwählen statt jede anzunehmen. Genau das schauen wir uns im Experten-Call an.' },
      { objection: 'Keine Zeit.', response: 'Deshalb halten wir es kurz: 30 Minuten, konkretes Feedback, keine Verkaufsshow. Wann passt es Ihnen besser — Anfang oder Ende der Woche?' },
    ],
  }),
  makeScript({
    id: 'script-2',
    role: 'Opener',
    title: 'Opener — Genereller Erstkontakt (lokal)',
    entry_angle: null,
    situation: 'standard_lokal',
    relevance_line: 'Wir arbeiten mit Unternehmen aus der Region und mir ist Ihr Betrieb positiv aufgefallen.',
    core_question: 'Was ist bei Ihnen aktuell der größte Engpass — Sichtbarkeit, Anfragen oder Zeit im Tagesgeschäft?',
    transition_line: 'Dazu machen wir einen kostenfreien Experten-Call mit konkretem fachlichem Feedback — ohne Verpflichtung.',
    call_goal: 'Experten-Call-Termin vereinbaren',
    objection_handling: [
      { objection: 'Schicken Sie mir Infos per Mail.', response: 'Mache ich gern — damit die Infos nicht generisch sind: Was wäre für Sie das wichtigste Thema? … Dann bringt der 30-Minuten-Call Ihnen aber deutlich mehr, denn da bekommen Sie eine echte Einschätzung.' },
    ],
  }),
  makeScript({
    id: 'script-3',
    role: 'Opener',
    title: 'Opener — KI & Zeitersparnis',
    entry_angle: 'KI-Zeitersparnis',
    situation: 'ki_automation',
    relevance_line: 'Viele Betriebe Ihrer Größe verlieren pro Woche einen ganzen Arbeitstag an vermeidbare Verwaltungsarbeit.',
    core_question: 'Welche Aufgabe frisst bei Ihnen intern am meisten Zeit, ohne Wert zu schaffen?',
    transition_line: 'Genau solche Abläufe analysiert unser Experte im kostenfreien KI-Experten-Call — mit ehrlicher Einschätzung, was sich wirklich lohnt.',
    call_goal: 'Experten-Call-Termin vereinbaren',
    objection_handling: [
      { objection: 'KI ist nichts für uns.', response: 'Das sagen viele — bis sie sehen, dass es nicht um Roboter geht, sondern darum, dass Angebote nicht mehr 3 Tage liegen bleiben. Genau das prüfen wir im Call, kostenlos.' },
    ],
  }),
]
